Added atlus fbn and hbn (Sierra)
TGEnigma/010-Editor-Templates pull request #17
Opened 2020-12-13 02:47 UTC by Tupelov

2020-12-17 21:31 UTC, TGEnigma requested changes
Thanks for your contribution, however there are some issues:
* Name tags are overall very inconsistent. Either name all of them or none at all, and ensure it is similar to the field name. I personally don't think they add anything of value in most cases.
* The naming convention is inconsistent. Use PascalCase, so no underscores and no names starting with a lowercase character.

2020-12-17 21:31 UTC, TGEnigma commented on templates/atlus_fbn.bt
> +typedef struct TableSegment
This is not a good name for this struct as it's not represenative of its contents.

2020-12-17 21:31 UTC, TGEnigma commented on templates/atlus_hbn.bt
> +typedef struct TableSegment
This is not a good name for this struct as it's not represenative of its contents.

2020-12-17 21:31 UTC, TGEnigma commented on templates/atlus_hbn.bt
> +	u32 Num_Of_Type_1_Entries <name = "Number of Type 1 Entries">;
The name comments don't match the field name

2021-01-04 10:59 UTC, TGEnigma commented
Any updates?

2021-02-05 15:12 UTC, TGEnigma requested changes

2021-02-05 15:12 UTC, TGEnigma commented on templates/atlus_fbn.bt
> +typedef struct TableSegment
Name should be FbnFile or something equivalent that represents the contents better

2021-02-05 15:12 UTC, TGEnigma commented on templates/atlus_hbn.bt
> +typedef struct TableSegment
Name should be FbnFile or something equivalent that represents the contents better

2021-02-05 15:12 UTC, TGEnigma commented on templates/atlus_Nbin.bt
> +    FSkip(28);
Are the skipped sections always 0?

2021-02-05 15:12 UTC, TGEnigma commented on templates/atlus_Nbin.bt
> +FSeek(0);
The code at the end of the file doesn't make much sense to me. Why is this not part of the File struct?

2021-02-05 15:12 UTC, TGEnigma commented on templates/atlus_fbn.bt
> +	if (Type1EntrySize==320)
This variable doesn't exist in this scope, you should pass it to the struct constructor if you wish to use it

2021-02-05 21:03 UTC, Tupelov commented on templates/atlus_Nbin.bt
> +    FSkip(28);
These are always FFFFF

2021-02-05 21:37 UTC, Tupelov commented
Ok hopefully now

2021-02-05 21:41 UTC, merged